name: stabbyrogue
favicon: null
layout_spectrum: 0.19057
typography_spectrum: 0.1944
title: thoughts and actions of a stabby rogue
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfdf0'
    - '#000011'
    - '#3b4f8a'
    - '#6986cc'
    - '#c0cdf0'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
